Change in workflow

diff --git a/.github/workflows/deploy-s3.yaml b/.github/workflows/deploy-s3.yaml
--- a/.github/workflows/deploy-s3.yaml
+++ b/.github/workflows/deploy-s3.yaml
@@ -2,7 +2,7 @@ name: deploy-S3-infrastructure
 
 on:
   workflow_run:
-    workflows: ["deploy-ec2-infrastructure"]
+    workflows: ["deploy-s3-infrastructure"]
     types:
       - completed
 
@@ -30,13 +30,23 @@ jobs:
           echo "Resolved S3 Tag: $tag"
           echo "latest_tag=$tag" >> $GITHUB_OUTPUT
 
-      - name: Download latest release-s3.zip
-        uses: dsaltares/fetch-gh-release-asset@master
-        with:
-          repo: ${{ github.repository }}
-          file: release-s3.zip
-          target: release-s3.zip
-          token: ${{ secrets.SECRET_KEY }}
+      - name: Download release-s3.zip
+        run: |
+          tag=${{ steps.get_tag.outputs.latest_tag }}
+
+          asset_url=$(curl -s -H "Authorization: token ${{ secrets.SECRET_KEY }}" \
+            https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag \
+            | jq -r '.assets[] | select(.name == "release-s3.zip") | .url')
+
+          if [ -z "$asset_url" ]; then
+            echo "❌ Could not find asset URL."; exit 1
+          fi
+
+          curl -L -H "Authorization: token ${{ secrets.SECRET_KEY }}" \
+               -H "Accept: application/octet-stream" \
+                "$asset_url" -o release-s3.zip
+
+          echo "✅ Downloaded release-s3.zip"
 
       - name: Extract release-s3.zip
         run: unzip -o release-s3.zip -d terraform-s3bucket
