Change in workflow

diff --git a/.github/workflows/ec2-infrastructure.yaml b/.github/workflows/ec2-infrastructure.yaml
--- a/.github/workflows/ec2-infrastructure.yaml
+++ b/.github/workflows/ec2-infrastructure.yaml
@@ -40,9 +40,6 @@ jobs:
           terraform init  | tee init_output.txt
           echo "exitcode=$?" >> $GITHUB_OUTPUT
 
-      - name: Debug - Show init output
-        run: cat terraform-ec2/init_output.txt || echo "init_output.txt not found"
-
       - name: Setup TFLint
         uses: terraform-linters/setup-tflint@v4
         with:
@@ -58,6 +55,10 @@ jobs:
         run: |
           tflint -f compact | tee tflint_output.txt
           echo "exitcode=$?" >> $GITHUB_OUTPUT
+
+      - name: Cat TFLint
+        run: |
+          cat terraform-ec2/tflint_output.txt || echo "tflint_output.txt not found"
 
       - name: Comment Terraform TFLint
         uses: actions/github-script@v7
